### ISSUE TITLE
Demo question

### ISSUE THREAD

**Issue by mitulsavani** [BenBrewerBowman/MovieTickets_ReactNative#2]
Hey @BenBrewerBowman  I wonder what did you use to create that demo gif on your README?

Thanks

**Comment by BenBrewerBowman** [comment]
As much as I would love to take credit for it, it is actually part of the tutorial I followed. I just copied it from them to add to the readme. I would post this question there or see if someone has already asked it. Thanks for asking though and let me know what you find out bc it is a super cool gif!

The tutorial: https://github.com/rationalappdev/MovieTickets
